version: '3'
services:
  joomla:
    image: joomla:3.9.24-apache
    container_name: joomla_container
    depends_on:
      - mysql
    volumes:
      - "$PWD/content:/var/www/html"
    ports:
      - "9090:80"
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_NAME: joomla
    networks:
      - joomla_net
  mysql:
    image: mysql:5.7
    volumes: 
      - "$PWD/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: joomla
      MYSQL_DATABASE: joomla
      MYSQL_PASSWORD: joomla
    networks:
      - joomla_net
networks:
  joomla_net:
